spring:
  application:
    name: loot
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      maximum-pool-size: 10
